spring:
  application:
    name: ENotes_API_Service

  datasource:
    url: jdbc:mysql://localhost:3306/e_notes
    username: root
    password: 1999redmi3s

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    username: "abhosale5010@gmail.com"
    password: "wgch tsjz qteo mcru"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 

file:
  upload:
    path: notes/

jwt:
  secret: "myverystrongsecretkeymyverystrongsecretkey1234567890"

